### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.chatapp.User.getUuid()' on a null object reference

### ISSUE THREAD

**Issue by mskantiwal** [mskantiwal/ChatApp#1]
I am stucked in this error i don't know how to resolve this if someone know plz help.

ChatActivity.java 

`
public class ChatActivity extends AppCompatActivity {

    private GroupAdapter adapter;
    private User user;
    private User me;
    private EditText editChat;
    private ImageButton mSendBtn;

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile);

        if (savedInstanceState!=null){
            user = getIntent().getExtras().getParcelable("user");

        }else {
            Toast.makeText(this,"error",Toast.LENGTH_SHORT).show();
        }

        RecyclerView rv = findViewById(R.id.Chat_Recyclerview);

        editChat = findViewById(R.id.messageEt);
        mSendBtn = findViewById(R.id.send_Btn);

        adapter = new GroupAdapter();
        rv.setLayoutManager(new LinearLayoutManager(this));
        rv.setAdapter(adapter);

        FirebaseFirestore.getInstance().collection("/users")
                .document(FirebaseAuth.getInstance().getUid())
                .get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
            @Override
            public void onSuccess(DocumentSnapshot documentSnapshot) {
                me = documentSnapshot.toObject(User.class);
                fetchMessages();
            }
        });

        mSendBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                sendMessage();
            }
        });
    }

    private void fetchMessages() {

        if (me != null){
            String fromId = me.getUuid();
            String toId = user.getUuid();

            FirebaseFirestore.getInstance().collection("/conversations")
                    .document(fromId)
                    .collection(toId)
                    .orderBy("timestamp", Query.Direction.ASCENDING)
                    .addSnapshotListener(new EventListener<QuerySnapshot>() {
                        @Override
                        public void onEvent(@Nullable QuerySnapshot queryDocumentSnapshots, @Nullable FirebaseFirestoreException e) {
                            List<DocumentChange> documentChanges = queryDocumentSnapshots.getDocumentChanges();

                            if (documentChanges != null){
                                for (DocumentChange doc: documentChanges){
                                    if (doc.getType() == DocumentChange.Type.ADDED){
                                        Message message = doc.getDocument().toObject(Message.class);
                                        adapter.add(new MessageItem(message));
                                    }
                                }
                            }

                        }
                    });
        }
    }

    private void sendMessage() {

        String text =  editChat.getText().toString();

        editChat.setText(null);

        final String fromId = FirebaseAuth.getInstance().getUid();
        final String toId = user.getUuid();
        long timeStamp = System.currentTimeMillis();

        final Message message = new Message(text, timeStamp, fromId, toId);
        message.setFromID(fromId);
        message.setToID(toId);
        message.setTimestamp(timeStamp);
        message.setText(text);

        if (!message.getText().isEmpty()){
            FirebaseFirestore.getInstance().collection("/conversations")
                    .document(fromId)
                    .collection(toId)
                    .add(message)
                    .addOnSuccessListener(new OnSuccessListener<DocumentReference>() {
                        @Override
                        public void onSuccess(DocumentReference documentReference) {

                            Log.d("Test",documentReference.getId());

                            Contacts contact = new Contacts();
                            contact.setUuid(toId);

                            contact.setTimestamp(message.getTimestamp());
                            contact.setLastMessage(message.getText());

                            FirebaseFirestore.getInstance().collection("/last-messages")
                                    .document(fromId)
                                    .collection("contacts")
                                    .document(toId)
                                    .set(contact);
                        }
                    }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {

                    Log.e("Teste", e.getMessage(),e);
                }
            });
            FirebaseFirestore.getInstance().collection("/conversations")
                    .document(toId)
                    .collection(fromId)
                    .add(message)
                    .addOnSuccessListener(new OnSuccessListener<DocumentReference>() {
                        @Override
                        public void onSuccess(DocumentReference documentReference) {

                            Log.d("Test",documentReference.getId());

                            Contacts contact = new Contacts();
                            contact.setUuid(toId);
                            contact.setUsername(user.getName());

                            contact.setTimestamp(message.getTimestamp());
                            contact.setLastMessage(message.getText());

                            FirebaseFirestore.getInstance().collection("/last-messages")
                                    .document(toId)
                                    .collection("contacts")
                                    .document(fromId)
                                    .set(contact);

                        }
                    }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {

                    Log.e("Teste", e.getMessage(),e);
                }
            });

        }

    }
    private class MessageItem extends Item<ViewHolder>{

        private final Message message;

        private MessageItem(Message message) {
            this.message = message;
        }

        @Override
        public void bind(@NonNull ViewHolder viewHolder, int position) {

            TextView txtMsg = viewHolder.itemView.findViewById(R.id.txt_msg);
            ImageView imgMessage = viewHolder.itemView.findViewById(R.id.img_message_user);

            txtMsg.setText(message.getText());

        }

        @Override
        public int getLayout() {
            return  message.getFromID().equals(FirebaseAuth.getInstance().getUid())
                    ? R.layout.item_from_message
                    : R.layout.item_to_message;
        }
    }
}
`
message.java class
`
public class Message  {

    public Message(){}

    private String text;
    private long timestamp;
    private String fromID;
    private String toID;

    public Message(String text, long timestamp, String fromID, String toID) {
        this.text = text;
        this.timestamp = timestamp;
        this.fromID = fromID;
        this.toID = toID;
    }

    protected Message(Parcel in) {
        text = in.readString();
        timestamp = in.readLong();
        fromID = in.readString();
        toID = in.readString();
    }

    public String getToID() {
        return toID;
    }

    public void setToID(String toID) {
        this.toID = toID;
    }

    public String getFromID() {
        return fromID;
    }

    public void setFromID(String fromID) {
        this.fromID = fromID;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public void getFromId() {

}

}
`

contacts.java
`
public class Contacts  {

public Contacts(){}

    private String uuid;
    private String username;
    private String lastMessage;
    private String photoUrl;

    public Contacts(String uuid, String username, String lastMessage, String photoUrl) {
        this.uuid = uuid;
        this.username = username;
        this.lastMessage = lastMessage;
        this.photoUrl = photoUrl;
    }

    protected Contacts(Parcel in) {
        uuid = in.readString();
        username = in.readString();
        lastMessage = in.readString();
        photoUrl = in.readString();
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public void setTimestamp(long timestamp) {

    }
}
`

Users.java
`
public class User  {

    public User(){}

    public User(String uuid, String name, String status){
        this.uuid = uuid;
        this.name = name;
        this.status = status;
    }
    private String uuid;
    private String name;
    private String status;

    protected User(Parcel in) {
        uuid = in.readString();
        name = in.readString();
        status = in.readString();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}

`

**Comment by mskantiwal** [comment]
Logcat
`2020-07-06 07:30:57.012 18322-18322/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-07-06 07:30:57.014 18322-18322/? E/Zygote: accessInfo : 1
2020-07-06 07:30:57.049 18322-18322/? E/example.chatap: Unknown bits set in runtime_flags: 0x8000
2020-07-06 07:31:02.803 18322-18322/com.example.chatapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.chatapp, PID: 18322
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.chatapp.User.getUuid()' on a null object reference
        at com.example.chatapp.ChatActivity.sendMessage(ChatActivity.java:133)
        at com.example.chatapp.ChatActivity.access$200(ChatActivity.java:37)
        at com.example.chatapp.ChatActivity$2.onClick(ChatActivity.java:91)
        at android.view.View.performClick(View.java:7870)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
`
